# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arts_Explorer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Arts_Explorer

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

  target 'Arts_ExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Arts_ExplorerUITests' do
    # Pods for testing
  end

end
